version: "3.9"
services:
  app:
    image: antgoncharik/crypto-knight-gateway
    restart: always
    networks:
      - share-net
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - share-net
volumes:
  caddy_data:
  caddy_config:
networks:
  share-net:
    external: true
